baseURL = "https://amandamuller.netlify.com/"
title = "amandamuller"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "pt-br"
enableEmoji = true

[pagination]
pagerSize = 6

[markup.highlight]
noClasses = false

[params]
author = "Amanda Muller"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Amanda Muller's personal website"
keywords = "blog,digital,mother"
info = ["Digital Nomad","Software Engineer", "Mother"]
avatarURL = "images/avatar.jpg"
#gravatar = "amandaeleomuller@gmail.com"
dateFormat = "January 2, 2006"
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)(default)
# "light" (light background, dark foreground) 
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Instagram"
icon = "fa-brands fa-instagram fa-2x"
weight = 1
url = "https://www.instagram.com/amndmuller/"

[[params.social]]
name = "TikTok"
icon = "fa-brands fa-tiktok fa-2x"
weight = 1
url = "https://www.tiktok.com/@amndmuller"

[[params.social]]
name = "Youtube"
icon = "fa-brands fa-youtube fa-2x"
weight = 5
url = "https://www.youtube.com/@amandaeleo"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/carneiro-amanda/"


[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 5
url = "https://acarneiro.medium.com/"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/amandacarneiro"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 6
url = "https://myhugosite.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[languages.pt-br]
languageName = ":brazil:"
title = "Amanda Muller"

[languages.pt-br.params]
author = "Amanda Muller"
info = ["Nômade digital", "Engenheira de Software", "Mãe"]
description = "Blog pessoal de Amanda Muller"
keywords = "blog, nomade, maternidade, desenvolvedor"

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

[[languages.pt-br.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.pt-br.menu.main]]
name = "Projetos"
weight = 3
url = "projects/"

[[languages.pt-br.menu.main]]
name = "Contato"
weight = 5
url = "contact/"
